// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package tutorial

import (
	"database/sql"
	"time"
)

type Cuthistory struct {
	ID             int64
	ThisIsCut      bool
	LateTime       int32
	ListsID        int64
	ListsUpdatedAt time.Time
}

type Cutlist struct {
	ID        int64
	ThisIsCut bool
	UserID    int64
	Name      string
	Color     string
	Count     int32
	Limit     int32
	LateTime  int32
	LateCount int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Eventhistory struct {
	ID             int64
	ListsID        int64
	ListsUpdatedAt time.Time
}

type Eventlist struct {
	ID        int64
	UserID    int64
	Name      string
	Color     string
	Count     int32
	Limit     int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type User struct {
	ID   int64
	Uuid string
}
