// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package tutorial

import (
	"context"
	"time"
)

const createCutHistory = `-- name: CreateCutHistory :exec
INSERT INTO cutHistory (this_is_cut, late_time, lists_id, lists_updated_at)
VALUES (?, ?, ?, ?)
`

type CreateCutHistoryParams struct {
	ThisIsCut      bool
	LateTime       int32
	ListsID        int64
	ListsUpdatedAt time.Time
}

func (q *Queries) CreateCutHistory(ctx context.Context, arg CreateCutHistoryParams) error {
	_, err := q.db.ExecContext(ctx, createCutHistory,
		arg.ThisIsCut,
		arg.LateTime,
		arg.ListsID,
		arg.ListsUpdatedAt,
	)
	return err
}

const createCutList = `-- name: CreateCutList :exec
INSERT INTO cutLists (this_is_cut, user_id, name, color, count, ` + "`" + `limit` + "`" + `, late_time, late_count)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCutListParams struct {
	ThisIsCut bool
	UserID    int64
	Name      string
	Color     string
	Count     int32
	Limit     int32
	LateTime  int32
	LateCount int32
}

func (q *Queries) CreateCutList(ctx context.Context, arg CreateCutListParams) error {
	_, err := q.db.ExecContext(ctx, createCutList,
		arg.ThisIsCut,
		arg.UserID,
		arg.Name,
		arg.Color,
		arg.Count,
		arg.Limit,
		arg.LateTime,
		arg.LateCount,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (uuid)
VALUES (?)
`

func (q *Queries) CreateUser(ctx context.Context, uuid string) error {
	_, err := q.db.ExecContext(ctx, createUser, uuid)
	return err
}

const deleteCutHistory = `-- name: DeleteCutHistory :exec
DELETE FROM cutHistory
WHERE lists_id = ?
`

func (q *Queries) DeleteCutHistory(ctx context.Context, listsID int64) error {
	_, err := q.db.ExecContext(ctx, deleteCutHistory, listsID)
	return err
}

const deleteCutList = `-- name: DeleteCutList :exec
DELETE FROM cutLists
WHERE id = ?
`

func (q *Queries) DeleteCutList(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCutList, id)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, uuid
FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Uuid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCutHistory = `-- name: GetCutHistory :many
SELECT id, this_is_cut, late_time, lists_id, lists_updated_at
FROM cutHistory
WHERE lists_id = ?
ORDER BY lists_updated_at DESC
`

func (q *Queries) GetCutHistory(ctx context.Context, listsID int64) ([]Cuthistory, error) {
	rows, err := q.db.QueryContext(ctx, getCutHistory, listsID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cuthistory
	for rows.Next() {
		var i Cuthistory
		if err := rows.Scan(
			&i.ID,
			&i.ThisIsCut,
			&i.LateTime,
			&i.ListsID,
			&i.ListsUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCutLists = `-- name: GetCutLists :many
SELECT id, this_is_cut, user_id, name, color, count, ` + "`" + `limit` + "`" + `, late_time, late_count, created_at, updated_at
FROM cutLists
WHERE user_id = ?
`

func (q *Queries) GetCutLists(ctx context.Context, userID int64) ([]Cutlist, error) {
	rows, err := q.db.QueryContext(ctx, getCutLists, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cutlist
	for rows.Next() {
		var i Cutlist
		if err := rows.Scan(
			&i.ID,
			&i.ThisIsCut,
			&i.UserID,
			&i.Name,
			&i.Color,
			&i.Count,
			&i.Limit,
			&i.LateTime,
			&i.LateCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventHistory = `-- name: GetEventHistory :many
SELECT id, lists_id, lists_updated_at
FROM eventHistory
WHERE lists_id = ?
ORDER BY lists_updated_at DESC
`

func (q *Queries) GetEventHistory(ctx context.Context, listsID int64) ([]Eventhistory, error) {
	rows, err := q.db.QueryContext(ctx, getEventHistory, listsID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Eventhistory
	for rows.Next() {
		var i Eventhistory
		if err := rows.Scan(&i.ID, &i.ListsID, &i.ListsUpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventLists = `-- name: GetEventLists :many
SELECT id, user_id, name, color, count, ` + "`" + `limit` + "`" + `, created_at, updated_at
FROM eventLists
WHERE user_id = ?
`

func (q *Queries) GetEventLists(ctx context.Context, userID int64) ([]Eventlist, error) {
	rows, err := q.db.QueryContext(ctx, getEventLists, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Eventlist
	for rows.Next() {
		var i Eventlist
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Color,
			&i.Count,
			&i.Limit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id
FROM users
WHERE uuid = ?
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, uuid string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUser, uuid)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateCutListCount = `-- name: UpdateCutListCount :exec
UPDATE cutLists
SET count = ?
WHERE id = ?
`

type UpdateCutListCountParams struct {
	Count int32
	ID    int64
}

func (q *Queries) UpdateCutListCount(ctx context.Context, arg UpdateCutListCountParams) error {
	_, err := q.db.ExecContext(ctx, updateCutListCount, arg.Count, arg.ID)
	return err
}
