// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: test.proto

package pkg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqcreateUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqcreateUser) Reset() {
	*x = ReqcreateUser{}
	mi := &file_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqcreateUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqcreateUser) ProtoMessage() {}

func (x *ReqcreateUser) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqcreateUser.ProtoReflect.Descriptor instead.
func (*ReqcreateUser) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

func (x *ReqcreateUser) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type RescreateUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // AUTO_INCREMENT で生成された id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RescreateUser) Reset() {
	*x = RescreateUser{}
	mi := &file_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RescreateUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RescreateUser) ProtoMessage() {}

func (x *RescreateUser) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RescreateUser.ProtoReflect.Descriptor instead.
func (*RescreateUser) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1}
}

func (x *RescreateUser) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReqCreateCutList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThisIsCut     bool                   `protobuf:"varint,1,opt,name=this_is_cut,json=thisIsCut,proto3" json:"this_is_cut,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	Count         int64                  `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	Limit         int64                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	LateTime      int64                  `protobuf:"varint,7,opt,name=late_time,json=lateTime,proto3" json:"late_time,omitempty"` // 例: "2025-01-01 12:00:00"
	LateCount     int64                  `protobuf:"varint,8,opt,name=late_count,json=lateCount,proto3" json:"late_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqCreateCutList) Reset() {
	*x = ReqCreateCutList{}
	mi := &file_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqCreateCutList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqCreateCutList) ProtoMessage() {}

func (x *ReqCreateCutList) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqCreateCutList.ProtoReflect.Descriptor instead.
func (*ReqCreateCutList) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{2}
}

func (x *ReqCreateCutList) GetThisIsCut() bool {
	if x != nil {
		return x.ThisIsCut
	}
	return false
}

func (x *ReqCreateCutList) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReqCreateCutList) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReqCreateCutList) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *ReqCreateCutList) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ReqCreateCutList) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ReqCreateCutList) GetLateTime() int64 {
	if x != nil {
		return x.LateTime
	}
	return 0
}

func (x *ReqCreateCutList) GetLateCount() int64 {
	if x != nil {
		return x.LateCount
	}
	return 0
}

type ReqUpateCutList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ThisIsCut     bool                   `protobuf:"varint,2,opt,name=this_is_cut,json=thisIsCut,proto3" json:"this_is_cut,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	Count         int64                  `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	Limit         int64                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	LateTime      int64                  `protobuf:"varint,7,opt,name=late_time,json=lateTime,proto3" json:"late_time,omitempty"` // 例: "2025-01-01 12:00:00"
	LateCount     int64                  `protobuf:"varint,8,opt,name=late_count,json=lateCount,proto3" json:"late_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqUpateCutList) Reset() {
	*x = ReqUpateCutList{}
	mi := &file_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqUpateCutList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUpateCutList) ProtoMessage() {}

func (x *ReqUpateCutList) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUpateCutList.ProtoReflect.Descriptor instead.
func (*ReqUpateCutList) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{3}
}

func (x *ReqUpateCutList) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReqUpateCutList) GetThisIsCut() bool {
	if x != nil {
		return x.ThisIsCut
	}
	return false
}

func (x *ReqUpateCutList) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReqUpateCutList) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *ReqUpateCutList) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ReqUpateCutList) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ReqUpateCutList) GetLateTime() int64 {
	if x != nil {
		return x.LateTime
	}
	return 0
}

func (x *ReqUpateCutList) GetLateCount() int64 {
	if x != nil {
		return x.LateCount
	}
	return 0
}

type ResCreateCutList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // AUTO_INCREMENT で生成された id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResCreateCutList) Reset() {
	*x = ResCreateCutList{}
	mi := &file_test_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResCreateCutList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResCreateCutList) ProtoMessage() {}

func (x *ResCreateCutList) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResCreateCutList.ProtoReflect.Descriptor instead.
func (*ResCreateCutList) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{4}
}

func (x *ResCreateCutList) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReqGetUserByUuid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqGetUserByUuid) Reset() {
	*x = ReqGetUserByUuid{}
	mi := &file_test_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGetUserByUuid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetUserByUuid) ProtoMessage() {}

func (x *ReqGetUserByUuid) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetUserByUuid.ProtoReflect.Descriptor instead.
func (*ReqGetUserByUuid) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{5}
}

func (x *ReqGetUserByUuid) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type ResGetUserByUuid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResGetUserByUuid) Reset() {
	*x = ResGetUserByUuid{}
	mi := &file_test_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResGetUserByUuid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResGetUserByUuid) ProtoMessage() {}

func (x *ResGetUserByUuid) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResGetUserByUuid.ProtoReflect.Descriptor instead.
func (*ResGetUserByUuid) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{6}
}

func (x *ResGetUserByUuid) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReqGetCutList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqGetCutList) Reset() {
	*x = ReqGetCutList{}
	mi := &file_test_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGetCutList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetCutList) ProtoMessage() {}

func (x *ReqGetCutList) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetCutList.ProtoReflect.Descriptor instead.
func (*ReqGetCutList) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{7}
}

func (x *ReqGetCutList) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ResGetCutList struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ThisIsCut bool                   `protobuf:"varint,1,opt,name=this_is_cut,json=thisIsCut,proto3" json:"this_is_cut,omitempty"`
	Id        int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name      string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Color     string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	Count     int64                  `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	Limit     int64                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	// int64 late_time = 7;
	LateCount     int64  `protobuf:"varint,7,opt,name=late_count,json=lateCount,proto3" json:"late_count,omitempty"`
	CreatedAt     string `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResGetCutList) Reset() {
	*x = ResGetCutList{}
	mi := &file_test_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResGetCutList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResGetCutList) ProtoMessage() {}

func (x *ResGetCutList) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResGetCutList.ProtoReflect.Descriptor instead.
func (*ResGetCutList) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{8}
}

func (x *ResGetCutList) GetThisIsCut() bool {
	if x != nil {
		return x.ThisIsCut
	}
	return false
}

func (x *ResGetCutList) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResGetCutList) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResGetCutList) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *ResGetCutList) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ResGetCutList) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ResGetCutList) GetLateCount() int64 {
	if x != nil {
		return x.LateCount
	}
	return 0
}

func (x *ResGetCutList) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ResGetCutList) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ResGetCutListList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CutLists      []*ResGetCutList       `protobuf:"bytes,1,rep,name=cut_lists,json=cutLists,proto3" json:"cut_lists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResGetCutListList) Reset() {
	*x = ResGetCutListList{}
	mi := &file_test_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResGetCutListList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResGetCutListList) ProtoMessage() {}

func (x *ResGetCutListList) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResGetCutListList.ProtoReflect.Descriptor instead.
func (*ResGetCutListList) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{9}
}

func (x *ResGetCutListList) GetCutLists() []*ResGetCutList {
	if x != nil {
		return x.CutLists
	}
	return nil
}

type ReqGetCutHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListId        int64                  `protobuf:"varint,1,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqGetCutHistory) Reset() {
	*x = ReqGetCutHistory{}
	mi := &file_test_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGetCutHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetCutHistory) ProtoMessage() {}

func (x *ReqGetCutHistory) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetCutHistory.ProtoReflect.Descriptor instead.
func (*ReqGetCutHistory) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{10}
}

func (x *ReqGetCutHistory) GetListId() int64 {
	if x != nil {
		return x.ListId
	}
	return 0
}

type ResGetCutHistory struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ThisIsCut      bool                   `protobuf:"varint,2,opt,name=this_is_cut,json=thisIsCut,proto3" json:"this_is_cut,omitempty"`
	LateTime       int64                  `protobuf:"varint,3,opt,name=late_time,json=lateTime,proto3" json:"late_time,omitempty"`
	ListsUpdatedAt string                 `protobuf:"bytes,4,opt,name=lists_updated_at,json=listsUpdatedAt,proto3" json:"lists_updated_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResGetCutHistory) Reset() {
	*x = ResGetCutHistory{}
	mi := &file_test_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResGetCutHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResGetCutHistory) ProtoMessage() {}

func (x *ResGetCutHistory) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResGetCutHistory.ProtoReflect.Descriptor instead.
func (*ResGetCutHistory) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{11}
}

func (x *ResGetCutHistory) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResGetCutHistory) GetThisIsCut() bool {
	if x != nil {
		return x.ThisIsCut
	}
	return false
}

func (x *ResGetCutHistory) GetLateTime() int64 {
	if x != nil {
		return x.LateTime
	}
	return 0
}

func (x *ResGetCutHistory) GetListsUpdatedAt() string {
	if x != nil {
		return x.ListsUpdatedAt
	}
	return ""
}

func (x *ResGetCutHistory) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ReqGetEventList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqGetEventList) Reset() {
	*x = ReqGetEventList{}
	mi := &file_test_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGetEventList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetEventList) ProtoMessage() {}

func (x *ReqGetEventList) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetEventList.ProtoReflect.Descriptor instead.
func (*ReqGetEventList) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{12}
}

func (x *ReqGetEventList) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ResGetEventList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	Count         int64                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Limit         int64                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResGetEventList) Reset() {
	*x = ResGetEventList{}
	mi := &file_test_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResGetEventList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResGetEventList) ProtoMessage() {}

func (x *ResGetEventList) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResGetEventList.ProtoReflect.Descriptor instead.
func (*ResGetEventList) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{13}
}

func (x *ResGetEventList) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResGetEventList) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResGetEventList) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *ResGetEventList) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ResGetEventList) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ResGetEventList) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ResGetEventList) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ReqGetEventHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqGetEventHistory) Reset() {
	*x = ReqGetEventHistory{}
	mi := &file_test_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGetEventHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetEventHistory) ProtoMessage() {}

func (x *ReqGetEventHistory) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetEventHistory.ProtoReflect.Descriptor instead.
func (*ReqGetEventHistory) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{14}
}

func (x *ReqGetEventHistory) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ResGetEventHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResGetEventHistory) Reset() {
	*x = ResGetEventHistory{}
	mi := &file_test_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResGetEventHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResGetEventHistory) ProtoMessage() {}

func (x *ResGetEventHistory) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResGetEventHistory.ProtoReflect.Descriptor instead.
func (*ResGetEventHistory) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{15}
}

func (x *ResGetEventHistory) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResGetEventHistory) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_test_proto protoreflect.FileDescriptor

const file_test_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"test.proto\x12\btutorial\"#\n" +
	"\rreqcreateUser\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\x1f\n" +
	"\rrescreateUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xdd\x01\n" +
	"\x10ReqCreateCutList\x12\x1e\n" +
	"\vthis_is_cut\x18\x01 \x01(\bR\tthisIsCut\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x03R\x05count\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x03R\x05limit\x12\x1b\n" +
	"\tlate_time\x18\a \x01(\x03R\blateTime\x12\x1d\n" +
	"\n" +
	"late_count\x18\b \x01(\x03R\tlateCount\"\xd3\x01\n" +
	"\x0fReqUpateCutList\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1e\n" +
	"\vthis_is_cut\x18\x02 \x01(\bR\tthisIsCut\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x03R\x05count\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x03R\x05limit\x12\x1b\n" +
	"\tlate_time\x18\a \x01(\x03R\blateTime\x12\x1d\n" +
	"\n" +
	"late_count\x18\b \x01(\x03R\tlateCount\"\"\n" +
	"\x10ResCreateCutList\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"'\n" +
	"\x11req_getUserByUuid\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"#\n" +
	"\x11res_getUserByUuid\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\")\n" +
	"\x0ereq_getCutList\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\xf3\x01\n" +
	"\x0eres_getCutList\x12\x1e\n" +
	"\vthis_is_cut\x18\x01 \x01(\bR\tthisIsCut\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x03R\x05count\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x03R\x05limit\x12\x1d\n" +
	"\n" +
	"late_count\x18\a \x01(\x03R\tlateCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"K\n" +
	"\x12res_getCutListList\x125\n" +
	"\tcut_lists\x18\x01 \x03(\v2\x18.tutorial.res_getCutListR\bcutLists\",\n" +
	"\x11req_getCutHistory\x12\x17\n" +
	"\alist_id\x18\x01 \x01(\x03R\x06listId\"\xa9\x01\n" +
	"\x11res_getCutHistory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1e\n" +
	"\vthis_is_cut\x18\x02 \x01(\bR\tthisIsCut\x12\x1b\n" +
	"\tlate_time\x18\x03 \x01(\x03R\blateTime\x12(\n" +
	"\x10lists_updated_at\x18\x04 \x01(\tR\x0elistsUpdatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\"+\n" +
	"\x10req_getEventList\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\xb6\x01\n" +
	"\x10res_getEventList\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x03R\x05count\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x03R\x05limit\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\".\n" +
	"\x13req_getEventHistory\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"D\n" +
	"\x13res_getEventHistory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\tR\tupdatedAt2\xf2\x02\n" +
	"\x0eCutListService\x12>\n" +
	"\n" +
	"CreateUser\x12\x17.tutorial.reqcreateUser\x1a\x17.tutorial.rescreateUser\x12I\n" +
	"\rGetUserByUuid\x12\x1b.tutorial.req_getUserByUuid\x1a\x1b.tutorial.res_getUserByUuid\x12B\n" +
	"\n" +
	"GetCutList\x12\x18.tutorial.req_getCutList\x1a\x18.tutorial.res_getCutList0\x01\x12H\n" +
	"\n" +
	"GetHistory\x12\x1b.tutorial.req_getCutHistory\x1a\x1b.tutorial.res_getCutHistory0\x01\x12G\n" +
	"\rCreateCutList\x12\x1a.tutorial.ReqCreateCutList\x1a\x1a.tutorial.ResCreateCutList2\xf5\x01\n" +
	"\x10EventListService\x12I\n" +
	"\rGetUserByUuid\x12\x1b.tutorial.req_getUserByUuid\x1a\x1b.tutorial.res_getUserByUuid\x12H\n" +
	"\fGetEventList\x12\x1a.tutorial.req_getEventList\x1a\x1a.tutorial.res_getEventList0\x01\x12L\n" +
	"\n" +
	"GetHistory\x12\x1d.tutorial.req_getEventHistory\x1a\x1d.tutorial.res_getEventHistory0\x01B\aZ\x05./pkgb\x06proto3"

var (
	file_test_proto_rawDescOnce sync.Once
	file_test_proto_rawDescData []byte
)

func file_test_proto_rawDescGZIP() []byte {
	file_test_proto_rawDescOnce.Do(func() {
		file_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)))
	})
	return file_test_proto_rawDescData
}

var file_test_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_test_proto_goTypes = []any{
	(*ReqcreateUser)(nil),      // 0: tutorial.reqcreateUser
	(*RescreateUser)(nil),      // 1: tutorial.rescreateUser
	(*ReqCreateCutList)(nil),   // 2: tutorial.ReqCreateCutList
	(*ReqUpateCutList)(nil),    // 3: tutorial.ReqUpateCutList
	(*ResCreateCutList)(nil),   // 4: tutorial.ResCreateCutList
	(*ReqGetUserByUuid)(nil),   // 5: tutorial.req_getUserByUuid
	(*ResGetUserByUuid)(nil),   // 6: tutorial.res_getUserByUuid
	(*ReqGetCutList)(nil),      // 7: tutorial.req_getCutList
	(*ResGetCutList)(nil),      // 8: tutorial.res_getCutList
	(*ResGetCutListList)(nil),  // 9: tutorial.res_getCutListList
	(*ReqGetCutHistory)(nil),   // 10: tutorial.req_getCutHistory
	(*ResGetCutHistory)(nil),   // 11: tutorial.res_getCutHistory
	(*ReqGetEventList)(nil),    // 12: tutorial.req_getEventList
	(*ResGetEventList)(nil),    // 13: tutorial.res_getEventList
	(*ReqGetEventHistory)(nil), // 14: tutorial.req_getEventHistory
	(*ResGetEventHistory)(nil), // 15: tutorial.res_getEventHistory
}
var file_test_proto_depIdxs = []int32{
	8,  // 0: tutorial.res_getCutListList.cut_lists:type_name -> tutorial.res_getCutList
	0,  // 1: tutorial.CutListService.CreateUser:input_type -> tutorial.reqcreateUser
	5,  // 2: tutorial.CutListService.GetUserByUuid:input_type -> tutorial.req_getUserByUuid
	7,  // 3: tutorial.CutListService.GetCutList:input_type -> tutorial.req_getCutList
	10, // 4: tutorial.CutListService.GetHistory:input_type -> tutorial.req_getCutHistory
	2,  // 5: tutorial.CutListService.CreateCutList:input_type -> tutorial.ReqCreateCutList
	5,  // 6: tutorial.EventListService.GetUserByUuid:input_type -> tutorial.req_getUserByUuid
	12, // 7: tutorial.EventListService.GetEventList:input_type -> tutorial.req_getEventList
	14, // 8: tutorial.EventListService.GetHistory:input_type -> tutorial.req_getEventHistory
	1,  // 9: tutorial.CutListService.CreateUser:output_type -> tutorial.rescreateUser
	6,  // 10: tutorial.CutListService.GetUserByUuid:output_type -> tutorial.res_getUserByUuid
	8,  // 11: tutorial.CutListService.GetCutList:output_type -> tutorial.res_getCutList
	11, // 12: tutorial.CutListService.GetHistory:output_type -> tutorial.res_getCutHistory
	4,  // 13: tutorial.CutListService.CreateCutList:output_type -> tutorial.ResCreateCutList
	6,  // 14: tutorial.EventListService.GetUserByUuid:output_type -> tutorial.res_getUserByUuid
	13, // 15: tutorial.EventListService.GetEventList:output_type -> tutorial.res_getEventList
	15, // 16: tutorial.EventListService.GetHistory:output_type -> tutorial.res_getEventHistory
	9,  // [9:17] is the sub-list for method output_type
	1,  // [1:9] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		MessageInfos:      file_test_proto_msgTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
