// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: test.proto

package pkg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqGetUserByUuid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqGetUserByUuid) Reset() {
	*x = ReqGetUserByUuid{}
	mi := &file_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGetUserByUuid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetUserByUuid) ProtoMessage() {}

func (x *ReqGetUserByUuid) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetUserByUuid.ProtoReflect.Descriptor instead.
func (*ReqGetUserByUuid) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

func (x *ReqGetUserByUuid) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type ResGetUserByUuid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResGetUserByUuid) Reset() {
	*x = ResGetUserByUuid{}
	mi := &file_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResGetUserByUuid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResGetUserByUuid) ProtoMessage() {}

func (x *ResGetUserByUuid) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResGetUserByUuid.ProtoReflect.Descriptor instead.
func (*ResGetUserByUuid) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1}
}

func (x *ResGetUserByUuid) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReqGetCutList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqGetCutList) Reset() {
	*x = ReqGetCutList{}
	mi := &file_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGetCutList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetCutList) ProtoMessage() {}

func (x *ReqGetCutList) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetCutList.ProtoReflect.Descriptor instead.
func (*ReqGetCutList) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{2}
}

func (x *ReqGetCutList) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ResGetCutList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	Count         int64                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Limit         int64                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResGetCutList) Reset() {
	*x = ResGetCutList{}
	mi := &file_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResGetCutList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResGetCutList) ProtoMessage() {}

func (x *ResGetCutList) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResGetCutList.ProtoReflect.Descriptor instead.
func (*ResGetCutList) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{3}
}

func (x *ResGetCutList) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResGetCutList) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResGetCutList) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *ResGetCutList) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ResGetCutList) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ResGetCutList) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ResGetCutList) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ReqGetCutHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqGetCutHistory) Reset() {
	*x = ReqGetCutHistory{}
	mi := &file_test_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGetCutHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetCutHistory) ProtoMessage() {}

func (x *ReqGetCutHistory) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetCutHistory.ProtoReflect.Descriptor instead.
func (*ReqGetCutHistory) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{4}
}

func (x *ReqGetCutHistory) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ResGetCutHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResGetCutHistory) Reset() {
	*x = ResGetCutHistory{}
	mi := &file_test_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResGetCutHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResGetCutHistory) ProtoMessage() {}

func (x *ResGetCutHistory) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResGetCutHistory.ProtoReflect.Descriptor instead.
func (*ResGetCutHistory) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{5}
}

func (x *ResGetCutHistory) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResGetCutHistory) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ReqGetEventList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqGetEventList) Reset() {
	*x = ReqGetEventList{}
	mi := &file_test_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGetEventList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetEventList) ProtoMessage() {}

func (x *ReqGetEventList) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetEventList.ProtoReflect.Descriptor instead.
func (*ReqGetEventList) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{6}
}

func (x *ReqGetEventList) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ResGetEventList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	Count         int64                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Limit         int64                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResGetEventList) Reset() {
	*x = ResGetEventList{}
	mi := &file_test_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResGetEventList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResGetEventList) ProtoMessage() {}

func (x *ResGetEventList) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResGetEventList.ProtoReflect.Descriptor instead.
func (*ResGetEventList) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{7}
}

func (x *ResGetEventList) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResGetEventList) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResGetEventList) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *ResGetEventList) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ResGetEventList) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ResGetEventList) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ResGetEventList) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ReqGetEventHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqGetEventHistory) Reset() {
	*x = ReqGetEventHistory{}
	mi := &file_test_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGetEventHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetEventHistory) ProtoMessage() {}

func (x *ReqGetEventHistory) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetEventHistory.ProtoReflect.Descriptor instead.
func (*ReqGetEventHistory) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{8}
}

func (x *ReqGetEventHistory) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ResGetEventHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResGetEventHistory) Reset() {
	*x = ResGetEventHistory{}
	mi := &file_test_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResGetEventHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResGetEventHistory) ProtoMessage() {}

func (x *ResGetEventHistory) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResGetEventHistory.ProtoReflect.Descriptor instead.
func (*ResGetEventHistory) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{9}
}

func (x *ResGetEventHistory) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResGetEventHistory) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_test_proto protoreflect.FileDescriptor

const file_test_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"test.proto\x12\btutorial\"'\n" +
	"\x11req_getUserByUuid\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"#\n" +
	"\x11res_getUserByUuid\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\")\n" +
	"\x0ereq_getCutList\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\xb4\x01\n" +
	"\x0eres_getCutList\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x03R\x05count\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x03R\x05limit\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\",\n" +
	"\x11req_getCutHistory\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"B\n" +
	"\x11res_getCutHistory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\tR\tupdatedAt\"+\n" +
	"\x10req_getEventList\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\xb6\x01\n" +
	"\x10res_getEventList\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x03R\x05count\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x03R\x05limit\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\".\n" +
	"\x13req_getEventHistory\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"D\n" +
	"\x13res_getEventHistory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\tR\tupdatedAt2\xe9\x01\n" +
	"\x0eCutListService\x12I\n" +
	"\rGetUserByUuid\x12\x1b.tutorial.req_getUserByUuid\x1a\x1b.tutorial.res_getUserByUuid\x12B\n" +
	"\n" +
	"GetCutList\x12\x18.tutorial.req_getCutList\x1a\x18.tutorial.res_getCutList0\x01\x12H\n" +
	"\n" +
	"GetHistory\x12\x1b.tutorial.req_getCutHistory\x1a\x1b.tutorial.res_getCutHistory0\x012\xf5\x01\n" +
	"\x10EventListService\x12I\n" +
	"\rGetUserByUuid\x12\x1b.tutorial.req_getUserByUuid\x1a\x1b.tutorial.res_getUserByUuid\x12H\n" +
	"\fGetEventList\x12\x1a.tutorial.req_getEventList\x1a\x1a.tutorial.res_getEventList0\x01\x12L\n" +
	"\n" +
	"GetHistory\x12\x1d.tutorial.req_getEventHistory\x1a\x1d.tutorial.res_getEventHistory0\x01B\aZ\x05./pkgb\x06proto3"

var (
	file_test_proto_rawDescOnce sync.Once
	file_test_proto_rawDescData []byte
)

func file_test_proto_rawDescGZIP() []byte {
	file_test_proto_rawDescOnce.Do(func() {
		file_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)))
	})
	return file_test_proto_rawDescData
}

var file_test_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_test_proto_goTypes = []any{
	(*ReqGetUserByUuid)(nil),   // 0: tutorial.req_getUserByUuid
	(*ResGetUserByUuid)(nil),   // 1: tutorial.res_getUserByUuid
	(*ReqGetCutList)(nil),      // 2: tutorial.req_getCutList
	(*ResGetCutList)(nil),      // 3: tutorial.res_getCutList
	(*ReqGetCutHistory)(nil),   // 4: tutorial.req_getCutHistory
	(*ResGetCutHistory)(nil),   // 5: tutorial.res_getCutHistory
	(*ReqGetEventList)(nil),    // 6: tutorial.req_getEventList
	(*ResGetEventList)(nil),    // 7: tutorial.res_getEventList
	(*ReqGetEventHistory)(nil), // 8: tutorial.req_getEventHistory
	(*ResGetEventHistory)(nil), // 9: tutorial.res_getEventHistory
}
var file_test_proto_depIdxs = []int32{
	0, // 0: tutorial.CutListService.GetUserByUuid:input_type -> tutorial.req_getUserByUuid
	2, // 1: tutorial.CutListService.GetCutList:input_type -> tutorial.req_getCutList
	4, // 2: tutorial.CutListService.GetHistory:input_type -> tutorial.req_getCutHistory
	0, // 3: tutorial.EventListService.GetUserByUuid:input_type -> tutorial.req_getUserByUuid
	6, // 4: tutorial.EventListService.GetEventList:input_type -> tutorial.req_getEventList
	8, // 5: tutorial.EventListService.GetHistory:input_type -> tutorial.req_getEventHistory
	1, // 6: tutorial.CutListService.GetUserByUuid:output_type -> tutorial.res_getUserByUuid
	3, // 7: tutorial.CutListService.GetCutList:output_type -> tutorial.res_getCutList
	5, // 8: tutorial.CutListService.GetHistory:output_type -> tutorial.res_getCutHistory
	1, // 9: tutorial.EventListService.GetUserByUuid:output_type -> tutorial.res_getUserByUuid
	7, // 10: tutorial.EventListService.GetEventList:output_type -> tutorial.res_getEventList
	9, // 11: tutorial.EventListService.GetHistory:output_type -> tutorial.res_getEventHistory
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		MessageInfos:      file_test_proto_msgTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
