// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: test.proto

package pkg

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CutListService_GetUserByUuid_FullMethodName = "/tutorial.CutListService/GetUserByUuid"
	CutListService_GetCutList_FullMethodName    = "/tutorial.CutListService/GetCutList"
	CutListService_GetHistory_FullMethodName    = "/tutorial.CutListService/GetHistory"
)

// CutListServiceClient is the client API for CutListService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CutListServiceClient interface {
	GetUserByUuid(ctx context.Context, in *ReqGetUserByUuid, opts ...grpc.CallOption) (*ResGetUserByUuid, error)
	GetCutList(ctx context.Context, in *ReqGetCutList, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResGetCutList], error)
	GetHistory(ctx context.Context, in *ReqGetCutHistory, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResGetCutHistory], error)
}

type cutListServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCutListServiceClient(cc grpc.ClientConnInterface) CutListServiceClient {
	return &cutListServiceClient{cc}
}

func (c *cutListServiceClient) GetUserByUuid(ctx context.Context, in *ReqGetUserByUuid, opts ...grpc.CallOption) (*ResGetUserByUuid, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResGetUserByUuid)
	err := c.cc.Invoke(ctx, CutListService_GetUserByUuid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cutListServiceClient) GetCutList(ctx context.Context, in *ReqGetCutList, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResGetCutList], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CutListService_ServiceDesc.Streams[0], CutListService_GetCutList_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReqGetCutList, ResGetCutList]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CutListService_GetCutListClient = grpc.ServerStreamingClient[ResGetCutList]

func (c *cutListServiceClient) GetHistory(ctx context.Context, in *ReqGetCutHistory, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResGetCutHistory], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CutListService_ServiceDesc.Streams[1], CutListService_GetHistory_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReqGetCutHistory, ResGetCutHistory]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CutListService_GetHistoryClient = grpc.ServerStreamingClient[ResGetCutHistory]

// CutListServiceServer is the server API for CutListService service.
// All implementations must embed UnimplementedCutListServiceServer
// for forward compatibility.
type CutListServiceServer interface {
	GetUserByUuid(context.Context, *ReqGetUserByUuid) (*ResGetUserByUuid, error)
	GetCutList(*ReqGetCutList, grpc.ServerStreamingServer[ResGetCutList]) error
	GetHistory(*ReqGetCutHistory, grpc.ServerStreamingServer[ResGetCutHistory]) error
	mustEmbedUnimplementedCutListServiceServer()
}

// UnimplementedCutListServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCutListServiceServer struct{}

func (UnimplementedCutListServiceServer) GetUserByUuid(context.Context, *ReqGetUserByUuid) (*ResGetUserByUuid, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserByUuid not implemented")
}
func (UnimplementedCutListServiceServer) GetCutList(*ReqGetCutList, grpc.ServerStreamingServer[ResGetCutList]) error {
	return status.Error(codes.Unimplemented, "method GetCutList not implemented")
}
func (UnimplementedCutListServiceServer) GetHistory(*ReqGetCutHistory, grpc.ServerStreamingServer[ResGetCutHistory]) error {
	return status.Error(codes.Unimplemented, "method GetHistory not implemented")
}
func (UnimplementedCutListServiceServer) mustEmbedUnimplementedCutListServiceServer() {}
func (UnimplementedCutListServiceServer) testEmbeddedByValue()                        {}

// UnsafeCutListServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CutListServiceServer will
// result in compilation errors.
type UnsafeCutListServiceServer interface {
	mustEmbedUnimplementedCutListServiceServer()
}

func RegisterCutListServiceServer(s grpc.ServiceRegistrar, srv CutListServiceServer) {
	// If the following call panics, it indicates UnimplementedCutListServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CutListService_ServiceDesc, srv)
}

func _CutListService_GetUserByUuid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqGetUserByUuid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CutListServiceServer).GetUserByUuid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CutListService_GetUserByUuid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CutListServiceServer).GetUserByUuid(ctx, req.(*ReqGetUserByUuid))
	}
	return interceptor(ctx, in, info, handler)
}

func _CutListService_GetCutList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReqGetCutList)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CutListServiceServer).GetCutList(m, &grpc.GenericServerStream[ReqGetCutList, ResGetCutList]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CutListService_GetCutListServer = grpc.ServerStreamingServer[ResGetCutList]

func _CutListService_GetHistory_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReqGetCutHistory)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CutListServiceServer).GetHistory(m, &grpc.GenericServerStream[ReqGetCutHistory, ResGetCutHistory]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CutListService_GetHistoryServer = grpc.ServerStreamingServer[ResGetCutHistory]

// CutListService_ServiceDesc is the grpc.ServiceDesc for CutListService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CutListService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tutorial.CutListService",
	HandlerType: (*CutListServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserByUuid",
			Handler:    _CutListService_GetUserByUuid_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetCutList",
			Handler:       _CutListService_GetCutList_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetHistory",
			Handler:       _CutListService_GetHistory_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "test.proto",
}

const (
	EventListService_GetUserByUuid_FullMethodName = "/tutorial.EventListService/GetUserByUuid"
	EventListService_GetEventList_FullMethodName  = "/tutorial.EventListService/GetEventList"
	EventListService_GetHistory_FullMethodName    = "/tutorial.EventListService/GetHistory"
)

// EventListServiceClient is the client API for EventListService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventListServiceClient interface {
	GetUserByUuid(ctx context.Context, in *ReqGetUserByUuid, opts ...grpc.CallOption) (*ResGetUserByUuid, error)
	GetEventList(ctx context.Context, in *ReqGetEventList, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResGetEventList], error)
	GetHistory(ctx context.Context, in *ReqGetEventHistory, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResGetEventHistory], error)
}

type eventListServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventListServiceClient(cc grpc.ClientConnInterface) EventListServiceClient {
	return &eventListServiceClient{cc}
}

func (c *eventListServiceClient) GetUserByUuid(ctx context.Context, in *ReqGetUserByUuid, opts ...grpc.CallOption) (*ResGetUserByUuid, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResGetUserByUuid)
	err := c.cc.Invoke(ctx, EventListService_GetUserByUuid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventListServiceClient) GetEventList(ctx context.Context, in *ReqGetEventList, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResGetEventList], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventListService_ServiceDesc.Streams[0], EventListService_GetEventList_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReqGetEventList, ResGetEventList]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventListService_GetEventListClient = grpc.ServerStreamingClient[ResGetEventList]

func (c *eventListServiceClient) GetHistory(ctx context.Context, in *ReqGetEventHistory, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResGetEventHistory], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventListService_ServiceDesc.Streams[1], EventListService_GetHistory_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReqGetEventHistory, ResGetEventHistory]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventListService_GetHistoryClient = grpc.ServerStreamingClient[ResGetEventHistory]

// EventListServiceServer is the server API for EventListService service.
// All implementations must embed UnimplementedEventListServiceServer
// for forward compatibility.
type EventListServiceServer interface {
	GetUserByUuid(context.Context, *ReqGetUserByUuid) (*ResGetUserByUuid, error)
	GetEventList(*ReqGetEventList, grpc.ServerStreamingServer[ResGetEventList]) error
	GetHistory(*ReqGetEventHistory, grpc.ServerStreamingServer[ResGetEventHistory]) error
	mustEmbedUnimplementedEventListServiceServer()
}

// UnimplementedEventListServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventListServiceServer struct{}

func (UnimplementedEventListServiceServer) GetUserByUuid(context.Context, *ReqGetUserByUuid) (*ResGetUserByUuid, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserByUuid not implemented")
}
func (UnimplementedEventListServiceServer) GetEventList(*ReqGetEventList, grpc.ServerStreamingServer[ResGetEventList]) error {
	return status.Error(codes.Unimplemented, "method GetEventList not implemented")
}
func (UnimplementedEventListServiceServer) GetHistory(*ReqGetEventHistory, grpc.ServerStreamingServer[ResGetEventHistory]) error {
	return status.Error(codes.Unimplemented, "method GetHistory not implemented")
}
func (UnimplementedEventListServiceServer) mustEmbedUnimplementedEventListServiceServer() {}
func (UnimplementedEventListServiceServer) testEmbeddedByValue()                          {}

// UnsafeEventListServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventListServiceServer will
// result in compilation errors.
type UnsafeEventListServiceServer interface {
	mustEmbedUnimplementedEventListServiceServer()
}

func RegisterEventListServiceServer(s grpc.ServiceRegistrar, srv EventListServiceServer) {
	// If the following call panics, it indicates UnimplementedEventListServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventListService_ServiceDesc, srv)
}

func _EventListService_GetUserByUuid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqGetUserByUuid)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventListServiceServer).GetUserByUuid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventListService_GetUserByUuid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventListServiceServer).GetUserByUuid(ctx, req.(*ReqGetUserByUuid))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventListService_GetEventList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReqGetEventList)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventListServiceServer).GetEventList(m, &grpc.GenericServerStream[ReqGetEventList, ResGetEventList]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventListService_GetEventListServer = grpc.ServerStreamingServer[ResGetEventList]

func _EventListService_GetHistory_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReqGetEventHistory)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventListServiceServer).GetHistory(m, &grpc.GenericServerStream[ReqGetEventHistory, ResGetEventHistory]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventListService_GetHistoryServer = grpc.ServerStreamingServer[ResGetEventHistory]

// EventListService_ServiceDesc is the grpc.ServiceDesc for EventListService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventListService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tutorial.EventListService",
	HandlerType: (*EventListServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserByUuid",
			Handler:    _EventListService_GetUserByUuid_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetEventList",
			Handler:       _EventListService_GetEventList_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetHistory",
			Handler:       _EventListService_GetHistory_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "test.proto",
}
